name: Plana CI Workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  release:
    types:
      - created
jobs:
  gradle_build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - name: Assemble Debug
        run: |
        ./gradlew build