name: Plana CI Workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  release:
    types:
      - created
jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Gradle Build
        run: ./gradlew build