name: Plana CI Workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  release:
    types:
      - created
jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle Build
        run: |
          sudo apt install android-sdk
          ./gradlew build
