name: RickNMorty CI Workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  release:
    types:
      - created
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Project
        run: bash ./gradlew build
